export const packageId = "@audio-reader/auth" as const;

export { createFakePrincipal, type Principal, type PrincipalRole } from "./principal";
export {
  LOCAL_JWT_CONFIG,
  extractBearerToken,
  signAccessToken,
  validateAccessToken,
  type JwtClaims,
  type JwtFailureCode,
  type JwtSigningConfig,
  type JwtValidationResult,
  type SignAccessTokenClaims,
} from "./jwt";
export {
  createHostedAuthService,
  extractEmailOtp,
  type HostedAuthFetch,
  type HostedAuthServiceOptions,
  type HostedOtpMailer,
} from "./hosted-auth";
export {
  AUTH_PROVIDERS,
  createMemoryAuthService,
  normalizeEmail,
  type AuthFailureCode,
  type AuthIdentityStore,
  type AuthProviderId,
  type AuthResult,
  type AuthService,
  type AuthenticatedSession,
  type BootstrapDeviceInput,
  type BootstrapSession,
  type DeviceRevokeResult,
  type IdentityProvider,
  type LinkIdentityInput,
  type MemoryAuthServiceOptions,
  type OAuthAuthorizeInput,
  type OAuthExchangeInput,
  type OAuthProvider,
  type ProductDevice,
  type ProductProfile,
  type ProductSettings,
  type SessionTokens,
  type SettingsPutResult,
} from "./service";
export {
  DEFAULT_PASSWORDLESS_LIMITS,
  LOCAL_PASSWORDLESS_HMAC_SECRET,
  createCloudflareTurnstileVerifier,
  createDurablePasswordlessLimiter,
  createMemoryPasswordlessLimiter,
  hashIdentifier,
  type BlockedAttempt,
  type BucketLimit,
  type MemoryPasswordlessLimiterOptions,
  type PasswordlessAction,
  type PasswordlessAttempt,
  type PasswordlessDecision,
  type PasswordlessLimiter,
  type PasswordlessDurableStore,
  type PasswordlessLimits,
  type PasswordlessSecurityEvent,
  type TurnstileFetch,
  type TurnstileVerifier,
} from "./passwordless-limit";
